### PR TITLE
Correct command in CheckPortAvailable

### PR DESCRIPTION
**Pull request by farshidtz**

### CODE REVIEW

**Comment by farshidtz** [comment]
@MonicaisHer no idea why this has started failing. It passes locally and only failed on Github. Doubling the wait period did not help.

**Comment by MonicaisHer** [comment]
This PR should fix the issue: https://github.com/canonical/edgex-snap-testing/pull/19

**Comment by farshidtz** [comment]
@MonicaisHer thanks for debugging and the separate fix. Let's get this merged then.

> Local test uses ServiceChannel = "latest/edge", Github uses ServiceChannel = "1/edge.

I set the env var to `1/edge` when I tested locally.

**Comment by farshidtz** [comment]
> > @MonicaisHer thanks for debugging and the separate fix. Let's get this merged then.
> > > Local test uses ServiceChannel = "latest/edge", Github uses ServiceChannel = "1/edge.
> > 
> > 
> > I set the env var to `1/edge` when I tested locally.
> 
> Did you set both [L25](https://github.com/canonical/edgex-snap-testing/blob/main/test/suites/ekuiper/main_test.go#L25) and [L53](https://github.com/canonical/edgex-snap-testing/blob/main/test/suites/ekuiper/main_test.go#L53)?

What is the difference? They both use the same global variable which is populated by the `SERVICE_CHANNEL` environment variable [here](https://github.com/canonical/edgex-snap-testing/blob/9bb082f7950c8b37bf0ce522d5f4a90cafb05e67/test/utils/env.go#L26).

**Pull request merged**
